translations = {
	tr: {
		'bg_color_list_label'      : 'Zemin',
		'color_list_label'         : 'Renk',
		'font_family_list_label'   : 'Font',
		'font_size_list_label'     : 'Punto',
		'language_list_label'      : 'Dil',
		'madhab_list_label'        : 'İkindi',
		'method_list_label'        : 'Metod',
		'country_list_label'       : 'Ülke',
		'city_list_label'          : 'Şehir',
		'lat_input_label'          : 'Enlem',
		'lon_input_label'          : 'Boylam',
		'latitude'                 : 'Enlem',
		'longitude'                : 'Boylam',
		'location_map_label'       : 'Harita',
		'right_reset_btn'          : 'Reset',
		'get_location_btn'         : 'Lokasyon Bul',
		'date'                     : 'Tarih',
		'settings_header'          : 'Ayarlar',
		'header'                   : 'Namaz Vakitleri',
		'location_latitude_label'  : 'Enlem',
		'location_longitude_label' : 'Boylam',
		'location_header'          : 'Bulunduğunuz Yer',
		'location_settings_header' : 'Yer Ayarları',
		'methods' : {
			'MuslimWorldLeague': 'Dünya Müslüman Birliği',
			'Turkey': 'Diyanet İşleri Başkanlığı, Türkiye',
			'NorthAmerica': 'Kuzey Amerika İslam Birliği (ISNA)',
			'Dubai': 'Dubai',
			'Egyptian': 'Mısır Genel Gözlem Kurumu',
			'Karachi': 'İslami Bilimler Üniversitesi, Karaçi',
			'Kuwait': 'Kuveyt',
			'MoonsightingCommittee': 'Ay Gözlem Komitesi',
			'Qatar': 'Katar',
			'Singapore': 'Singapur',
			'Tehran': 'Jeofizik Enstitüsü, Tahran Üniversitesi',
			'UmmAlQura': 'Ümmül Kura Üniversitesi, Mekke',
			'Other': 'Özel Hesaplama Yöntemi',
		},
		'madhabs' : {
			'Hanafi' : 'Hanefi',
			'Shafi'  : 'Şafi',
			},
		'prayer_names' : {
			'fajr'    : 'İmsak',
			'sunrise' : 'Güneş',
			'dhuhr'   : 'Öğle',
			'asr'     : 'İkindi',
			'maghrib' : 'Akşam',
			'isha'    : 'Yatsı',
			},
		'months' : {
			'0' : 'Ocak',
			'1' : 'Şubat',
			'2' : 'Mart',
			'3' : 'Nisan',
			'4' : 'Mayıs',
			'5' : 'Haziran',
			'6' : 'Temmuz',
			'7' : 'Ağustos',
			'8' : 'Eylül',
			'9' : 'Ekim',
			'10': 'Kasım',
			'11': 'Aralık',
			},
		'days' : {
			'0' : 'Pazar',
			'1' : 'Pazartesi',
			'2' : 'Salı',
			'3' : 'Çarşamba',
			'4' : 'Perşembe',
			'5' : 'Cuma',
			'6' : 'Cumartesi',
			},
	},

	en: {
		'bg_color_list_label'      : 'Background',
		'color_list_label'         : 'Color',
		'font_family_list_label'   : 'Font',
		'font_size_list_label'     : 'Font Size',
		'language_list_label'      : 'Language',
		'right_reset_btn'          : 'Reset',
		'get_location_btn'         : 'Get Location',
		'madhab_list_label'        : 'Asr',
		'method_list_label'        : 'Method',
		'country_list_label'       : 'Country',
		'city_list_label'          : 'City',
		'lat_input_label'          : 'Latitude',
		'lon_input_label'          : 'Longitude',
		'latitude'                 : 'Latitude',
		'longitude'                : 'Longitude',
		'location_map_label'       : 'Map',
		'date'                     : 'Date',
		'settings_header'          : 'Settings',
		'header'                   : 'Prayer Times',
		'location_header'          : 'Your Location',
		'location_latitude_label'  : 'Latitude',
		'location_longitude_label' : 'Longitude',
		'location_settings_header' : 'Location Settings',
		'methods' : {
			'MuslimWorldLeague': 'Muslim World League',
			'Turkey': 'Presidency of Religious Affairs, Turkey',
			'NorthAmerica': 'Islamic Society of North America (ISNA)',
			'Dubai': 'Dubai',
			'Egyptian': 'Egyptian General Authority of Survey',
			'Karachi': 'University of Islamic Sciences, Karachi',
			'Kuwait': 'Kuwait',
			'MoonsightingCommittee': 'Moonsighting Committee',
			'Qatar': 'Qatar',
			'Singapore': 'Singapore',
			'Tehran': 'Institute of Geophysics, University of Tehran',
			'UmmAlQura': 'Umm al-Qura University, Makkah',
			'Other': 'Custom Calculation Method',
		},
		'madhabs' : {
			'Hanafi' : 'Hanafi',
			'Shafi'  : 'Shafi',
			},
		'prayer_names' : {
			'fajr'    : 'Fajr',
			'sunrise' : 'Sunrise',
			'dhuhr'   : 'Dhuhr',
			'asr'     : 'Asr',
			'maghrib' : 'Maghrib',
			'isha'    : 'Isha',
			},
		'months' : {
			'0' : 'January',
			'1' : 'February',
			'2' : 'March',
			'3' : 'April',
			'4' : 'May',
			'5' : 'June',
			'6' : 'July',
			'7' : 'August',
			'8' : 'September',
			'9' : 'October',
			'10': 'November',
			'11': 'December',
			},
		'days' : {
			'0' : 'Sunday',
			'1' : 'Monday',
			'2' : 'Tuesday',
			'3' : 'Wednesday',
			'4' : 'Thursday',
			'5' : 'Friday',
			'6' : 'Saturday',
			},
	},
};
