translations = {
	tr: {
	'juz_anchor_label'       : 'Cüz ',
	'page_anchor_label'      : 's ',
	'bg_color_list_label'    : 'Zemin',
	'color_list_label'       : 'Renk',
	'font_family_list_label' : 'Font',
	'font_size_list_label'   : 'Punto',
	'goto_page_btn'          : 'Git',
	'juz_list_label'         : 'Cüz',
	'language_list_label'    : 'Dil',
	'page_input_label'       : 'Sayfa',
	'reset_btn'              : 'Reset',
	'sura_list_label'        : 'Sûre',
	'sura_shortcuts_label'   : 'Kısayollar',
	'confirm_delete_bookmark': 'Yer işaretini silmek istiyor musunuz?',
	'page_info_page'         : 'syf',
	'page_info_juz'          : 'cz',
	'page_info_hizb'         : 'hzb',
	'date'                   : 'Tarih',
	'prayer_names'           : {
		'fajr'    : 'İmsak',
		'sunrise' : 'Güneş',
		'dhuhr'   : 'Öğle',
		'asr'     : 'İkindi',
		'maghrib' : 'Akşam',
		'isha'    : 'Yatsı',
	},
	'months'                 : {
		'0' : 'Ocak',
		'1' : 'Şubat',
		'2' : 'Mart',
		'3' : 'Nisan',
		'4' : 'Mayıs',
		'5' : 'Haziran',
		'6' : 'Temmuz',
		'7' : 'Ağustos',
		'8' : 'Eylül',
		'9' : 'Ekim',
		'10': 'Kasım',
		'11': 'Aralık',
		},
	},

	en: {
	'juz_anchor_label'       : 'Juz ',
	'page_anchor_label'      : 'p ',
	'bg_color_list_label'    : 'Background',
	'color_list_label'       : 'Color',
	'font_family_list_label' : 'Font',
	'font_size_list_label'   : 'Font Size',
	'goto_page_btn'          : 'Go',
	'juz_list_label'         : 'Juz',
	'language_list_label'    : 'Language',
	'page_input_label'       : 'Page',
	'reset_btn'              : 'Reset',
	'sura_list_label'        : 'Surah',
	'sura_shortcuts_label'   : 'Shortcuts',
	'confirm_delete_bookmark': 'Do you really want to delete bookmark?',
	'page_info_page'         : 'pg',
	'page_info_juz'          : 'jz',
	'page_info_hizb'         : 'hzb',
	'date'                   : 'Date',
	'prayer_names'           : {
		'fajr'    : 'Fajr',
		'sunrise' : 'Sunrise',
		'dhuhr'   : 'Dhuhr',
		'asr'     : 'Asr',
		'maghrib' : 'Maghrib',
		'isha'    : 'Isha',
	},
	'months'                 : {
		'0' : 'January',
		'1' : 'February',
		'2' : 'March',
		'3' : 'April',
		'4' : 'May',
		'5' : 'June',
		'6' : 'July',
		'7' : 'August',
		'8' : 'September',
		'9' : 'October',
		'10': 'November',
		'11': 'December',
		},
	}
};
