translations = {
	tr: {
	'bg_color_list_label'      : 'Zemin',
	'color_list_label'         : 'Renk',
	'font_family_list_label'   : 'Font',
	'font_size_list_label'     : 'Punto',
	'language_list_label'      : 'Dil',
	'asr_list_label'           : 'İkindi',
	'method_list_label'        : 'Metod',
	'country_list_label'       : 'Ülke',
	'city_list_label'          : 'Şehir',
	'lat_input_label'          : 'Enlem',
	'lon_input_label'          : 'Boylam',
	'right_reset_btn'          : 'Reset',
	'date'                     : 'Tarih',
	'settings_header'          : 'Ayarlar',
	'location_settings_header' : 'Yer Ayarları',
	'methods' : {
		'mwl'     : 'Muslim World League',
		'isna'    : 'Kuzey Amerika İslam Birliği',
		'egypt'   : 'Mısır Genel Gözlem Kurumu',
		'makkah'  : 'Umm al-Qura Üniversitesi, Mekke',
		'karachi' : 'İslami Bilimler Üniversitesi, Karaçi',
		'tehran'  : 'Jeofizik Enstitüsü, Tahran Üniversitesi',
		'shia'    : 'Shia Ithna Ashari, Leva Research Institute, Qum',
	},
	'asr' : {
		'hanafi' : 'Hanefi',
		'shafi'   : 'Şafi',
		},
	'prayer_names' : {
		'fajr'    : 'İmsak',
		'sunrise' : 'Güneş',
		'dhuhr'   : 'Öğle',
		'asr'     : 'İkindi',
		'maghrib' : 'Akşam',
		'isha'    : 'Yatsı',
		},
	'months' : {
		'0' : 'Ocak',
		'1' : 'Şubat',
		'2' : 'Mart',
		'3' : 'Nisan',
		'4' : 'Mayıs',
		'5' : 'Haziran',
		'6' : 'Temmuz',
		'7' : 'Ağustos',
		'8' : 'Eylül',
		'9' : 'Ekim',
		'10': 'Kasım',
		'11': 'Aralık',
		},
	},

	en: {
	'bg_color_list_label'      : 'Background',
	'color_list_label'         : 'Color',
	'font_family_list_label'   : 'Font',
	'font_size_list_label'     : 'Font Size',
	'language_list_label'      : 'Language',
	'right_reset_btn'          : 'Reset',
	'asr_list_label'           : 'Asr',
	'method_list_label'        : 'Method',
	'country_list_label'       : 'Country',
	'city_list_label'          : 'City',
	'lat_input_label'          : 'Latitude',
	'lon_input_label'          : 'Longitude',
	'date'                     : 'Date',
	'settings_header'          : 'Settings',
	'location_settings_header' : 'Location Settings',
	'methods' : {
		'mwl'     : 'Muslim World League',
		'isna'    : 'Islamic Society of North America',
		'egypt'   : 'Egyptian General Authority of Survey',
		'makkah'  : 'Umm al-Qura University, Makkah',
		'karachi' : 'University of Islamic Sciences, Karachi',
		'tehran'  : 'Institute of Geophysics, University of Tehran',
		'shia'    : 'Shia Ithna Ashari, Leva Research Institute, Qum',
	},
	'asr' : {
		'hanafi' : 'Hanafi',
		'shafi'  : 'Shafi',
		},
	'prayer_names' : {
		'fajr'    : 'Fajr',
		'sunrise' : 'Sunrise',
		'dhuhr'   : 'Dhuhr',
		'asr'     : 'Asr',
		'maghrib' : 'Maghrib',
		'isha'    : 'Isha',
		},
	'months' : {
		'0' : 'January',
		'1' : 'February',
		'2' : 'March',
		'3' : 'April',
		'4' : 'May',
		'5' : 'June',
		'6' : 'July',
		'7' : 'August',
		'8' : 'September',
		'9' : 'October',
		'10': 'November',
		'11': 'December',
		},
	},
};
